# Generated by Django 5.1.7 on 2025-03-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
